#!/bin/bash
#

CheckProcess()
{  
	if [ "$1" = "" ]; then    
		return 1  
	fi    

	PROCESS_NUM=`ps cx | grep "$1" | awk '{print $5}' | grep "^$1$" | wc -l`  
	if [ $PROCESS_NUM -eq 0 ];  then    
		return 1  
	else    
		return 0  
	fi
}

NR=`cat /proc/sys/fs/nr_open`
FM=`cat /proc/sys/fs/file-max`
if [ $FM -ge $NR ]; then
  LM=$NR
else
  LM=$FM
fi

if [ $LM -ge 1048576 ]; then
  ulimit -n 1048576
else
  ulimit -n "$LM"
fi

RM=`cat /proc/sys/net/core/rmem_max`
if [ $RM -lt 8388608 ]; then
  sysctl -q -w net.core.rmem_max=8388608
fi

echo 1 > /proc/sys/net/ipv4/ip_forward
for filename in `ls /proc/sys/net/ipv4/conf/`
do
    if [[ $filename != lo ]]; then
       echo 0 > /proc/sys/net/ipv4/conf/$filename/send_redirects
    fi
done

while [ 1 ] ; do 
  CheckProcess "ctod" 
  CheckQQ_RET=$?
  if [ $CheckQQ_RET -eq 1 ]; then
    /cto2/ctod   
  fi 
  sleep 10
done
