#!/bin/bash
#build by duhaibin   
#2014.11.17
#crtmpserver     This shell script takes care of starting and stopping crtmpserver
#

# Source function library.
. /etc/init.d/functions

#PIDFILE="/var/run/crtmpserver.pid"
prog=crtmpserver
prog1=rtmp2http
lockfile=/var/lock/subsys/$prog
pidfile=/var/run/crtmpserver.pid
pidofnamed() {
        pidofproc -p "$pidfile" "$prog";
}
start() {
        [ "$EUID" != "0" ] && exit 4
        [ -x /usr/local/sbin/crtmpserver ] || exit 5
        [ -f /usr/local/etc/crtmpserver.cdn.lua ] || exit 6
        # Start daemons.
        echo -e "Starting $prog: "
	if [ -n "`pidofnamed`" ]; then
    	echo -e "$prog: already running"
	else
        touch $pidfile
        chown www.root $pidfile
	cd /home/update/core/
	daemon /usr/local/sbin/crtmpserver --pid=/var/run/crtmpserver.pid /usr/local/etc/crtmpserver.cdn.lua 
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch $lockfile
        return $RETVAL
	fi
}

stop() {
        [ "$EUID" != "0" ] && exit 4
        echo -e $"Shutting down $prog: "
        killproc $prog && killproc ${prog1}
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $lockfile $pidfile
        return $RETVAL
}


case "$1" in

  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 2
esac
exit $RETVAL
