1:查看工资高于2000的员工
SELECT ENAME，SAL
FROM EMP_LEE
WHERE SAL>2000
2:查看不是"CLERK"职位的员工
SELECT ENAME,JOB
FROM EMP_LEE
WHERE JOB<>'CLERK'
3:查看工资在1000-2500之间的员工
SELECT ENAME,SAL
FROM EMP_LEE
WHERE SAL BETWEEN 1000 AND 2500
4:查看名字是以K结尾的员工
SELECT ENAME
FROM EMP_LEE
WHERE ENAME LIKE '%K'
5:查看20,30号部门的员工
SELECT ENAME，DEPTNO
FROM EMP_LEE
WHERE DEPTNO IN(20，30)
6:查看奖金为NULL的员工
SELECT ENAME,COMM
FROM EMP_LEE
WHERE COMM IS NULL
7:查看年薪高于20000的员工
SELECT ENAME，SAL
FROM EMP_LEE
WHERE SAL*12>20000
8:查看公司共有多少种职位
SELECT COUNT(DISTINCT JOB)
FROM EMP_LEE

SELECT DISTINCT JOB
FROM EMP_LEE
9:按部门号从小到大排列查看员工
SELECT ENAME,DEPTNO
FROM EMP_LEE
ORDER BY DEPTNO
10:查看每个部门的最高，最低，平均工资，和工资总和
SELECT MAX(SAL),MIN(SAL),AVG(SAL),SUM(SAL),DEPTNO
FROM EMP_LEE
GROUP BY DEPTNO
11:查看平均工资高于2000的部门的最低薪水
SELECT MIN(SAL)，DEPTNO
FROM EMP_LEE
GROUP BY DEPTNO
HAVING AVG(SAL)>2000
12:查看在NEWYORK工作的员工
SELECT E.ENAME,D.LOC
FROM EMP_LEE E,DEPT D
WHERE  E.DEPTNO=D.DEPTNO
AND D.LOC='NEW YORK'
13:查看所有员工及所在部门信息，若该员工没有部门，则
    部门信息以NULL显示
UPDATE EMP_LEE
SET  DEPTNO=NULL
WHERE ENAME='SCOTT'
COMMIT

SELECT E.ENAME ,D.DNAME,D.DEPTNO
FROM EMP_LEE E,DEPT D
WHERE E.DEPTNO=D.DEPTNO(+)
14:查看ALLEN的上司是谁
SELECT E.ENAME,M.ENAME
FROM EMP_LEE E,EMP_LEE M
WHERE E.MGR=M.EMPNO
AND E.ENAME='ALLEN'

查看平均工资高于2000的部门所在地？
SELECT D.LOC,D.DNAME
FROM EMP_LEE E,DEPT D
WHERE E.DEPTNO=D.DEPTNO
GROUP BY D.DNAME,D.LOC
HAVING AVG(E.SAL)>2000



查看JONES的上司在哪个城市工作？
SELECT D.LOC,M.ENAME
FROM EMP_LEE E,EMP_LEE M,DEPT D
WHERE E.MGR=M.EMPNO
AND   M.DEPTNO=D.DEPTNO
AND   E.ENAME='JONES'



    
SELECT * FROM EMP_LEE













