CREATE TABLE Account(
  ID NUMBER(9)not null,
  RECOOBNDER_ID NUMBER(9),
  LOGIN_NAME VARCHAR2(30)not null,
  LOGIN_PASSWD VARCHAR2(8)not null,
  STATUS CHAR(1),
  CREATE_DATE DATE default SYSDATE,
  PAUSE_DATE DATE,
  CLOSE_DATE DATE,
  REAL_NAME VARCHAR2(20) not null,
  IDCARD_NO CHAR(18) not null,
  BIRTHDATE DATE,
  GENDER CHAR(1),
  OCCUPATION VARCHAR2(50),
  TELEPHONE  VARCHAR2(15) not null,
  EMALL VARCHAR2(50),
  MAILADDRESS VARCHAR2(50),
  ZIPCODE CHAR(6),
  QQ VARCHAR2(15),
  LAST_LOGIN_TIME DATE,
  LAST_LOGIN_IP VARCHAR2(15)
  
);
RENAME Account to t_account;
ALTER TABLE t_account ADD(
  bak VARCHAR2(50)
)
ALTER TABLE t_account MODIFY(
  bak VARCHAR(40) DEFAULT 'login'
)
ALTER TABLE t_account DROP(
  bak
)
INSERT INTO t_account (ID,LOGIN_NAME,LOGIN_PASSWD,CREATE_DATE
,REAL_NAME,IDCARD_NO,TELEPHONE)
VALUES(1,'shiyl','256528',TO_DATE('2008-1-28','YY-MM-DD'),'shiyuanli','410381194302256523',
13669351234)
DELETE FROM t_account
WHERE ID=1;
SELECT *FROM t_account
commit
DESC t_account
DELETE FROM t_account
WHERE ID=1;




