#!/bin/bash
#
# watchdog		Startup script for watchdog
#
# chkconfig: - 85 15
# description: watchdog is a tool for ats server
# processname: watchdog2
# config: /etc/watchdog/config/watchdog.json
# config: /etc/sysconfig/watchdog
# pidfile: /var/run/watchdog2.pid

# source function library.
. /etc/rc.d/init.d/functions

name="watchdog2"
exec="/usr/local/bin/$name"
prog=$(basename $exec)
pidfile="var/run/watchdog2.pid"
WATCHDOG_CONF="/etc/watchdog2/watchdog.json"

[ -e /etc/sysconfig/watchdog2 ] && . /etc/sysconfig/watchdog2

lockfile=/var/lock/subsys/watchdog2

start() {
	DAEMON_COREFILE_LIMIT="unlimited"
	[ -f $WATCHDOG_CONF ] || exit 6
	[ -x $exec ] || exit 5
	echo -n $"starting $name: "
	daemon $exec --daemon --configure $WATCHDOG_CONF
	retval=$?
	echo
	[ $retval -eq 0 ] && touch $lockfile
	return $retval
}

stop() {
	echo -n $"stopping $name: "
	echo -n "$prog"
	killproc $prog -9
	retval=$?
	echo
	[ $retval -eq 0 ] && rm -f $lockfile
	return $retval
}

restart() {
	stop
	start
}

reload() {
	false
}

rh_status() {
	status $prog
}

rh_status_q() {
	rh_status >/dev/null 2>&1
}

case "$1" in
	start)
		rh_status_q && exit 0
		$1
		;;
	stop)
		rh_status_q || exit 0
		$1
		;;
	restart)
		$1
		;;
	reload)
		rh_status_q || exit 7
		$1
		;;
	force-reload)
		force_reload
		ll
		;;
	status)
		rh_status
		;;
	condrestart|try-restart)
		rh_status_q || exit 0 
		restart
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart|condrestart|try_restart}"
		exit 2
esac
exit $?
