#!/bin/bash
# script:cto_install.sh
#
#
# (c) 2015 , Tianbiao Zu <zutianbian@letv.com>
#
# 该脚本用于安装并配置cto加速

##############################################################################
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
export PATH

a=`ps -ef|grep -e "/cto/bin/cfgd" -e "/cto/bin/linkd" -e "/usr/bin/python /usr/bin/cherryd -c cto.conf -i root -d"|grep -v grep|awk '{printf "%s ",$2}'`
kill -9 $a
/cto/bin/ctostart



