class systembase_front_dev{
  include systembase_front_dev::authorized_keys
  include systembase_front_dev::crond
#  include systembase_front_dev::crtmpserver
  include systembase_front_dev::ffmux
  include systembase_front_dev::hardinfo
  include systembase_front_dev::hostsdenyallow
  include systembase_front_dev::install
  include systembase_front_dev::profile
  include systembase_front_dev::service_stop
  include systembase_front_dev::service_start
  include systembase_front_dev::shellupdate
  include systembase_front_dev::smokeping
  include systembase_front_dev::sudoers
  include systembase_front_dev::sysctl
  include systembase_front_dev::tmpdir
  include systembase_front_dev::yumrepo
  include systembase_front_dev::dnsmasqservice
  include systembase_front_dev::dnsmasqinstall
  include systembase_front_dev::dnsmasqconf
  include systembase_front_dev::ntp_config
  include systembase_front_dev::ntp_service
  include systembase_front_dev::monit_config
  include systembase_front_dev::monit_service
  include systembase_front_dev::fsserver
  include systembase_front_dev::ssh_config
  include systembase_front_dev::ssh_service
  include systembase_front_dev::rsyslog_config
}
